### ISSUE TITLE
issue on qnap

### ISSUE THREAD

**Issue by killmasta93** [StarFleetCPTN/GoMFT#102]
Hi 
Currently trying to install on qnap with docker container, i had to docker build and changing 
only this part 
```

# Architecture-related build arguments
ARG TARGETOS=linux
ARG TARGETARCH=arm64
ARG TARGETVARIANT="armv7"

```
but were getting this error when we start the docker

```
gomft  | exec /entrypoint.sh: exec format error
gomft  | exec /entrypoint.sh: exec format error
gomft  | exec /entrypoint.sh: exec format error
gomft  | exec /entrypoint.sh: exec format error
gomft  | exec /entrypoint.sh: exec format error
gomft  | exec /entrypoint.sh: exec format error
gomft  | exec /entrypoint.sh: exec format error
gomft  | exec /entrypoint.sh: exec format error
gomft  | exec /entrypoint.sh: exec format error
```
the compose i have is 
```

version: '3'
services:
  gomft:
    image: gomftarmv7:latest
    container_name: gomft
    restart: unless-stopped
    ports:
      - "8580:8080"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      #- ./.env:/app/.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - SERVER_ADDRESS=:8080
      - DATA_DIR=/app/data
      - BACKUP_DIR=/app/backups
      - JWT_SECRET=change_this_to_a_secure_random_string
      - BASE_URL=http://localhost:8080
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - TOTP_ENCRYPTION_KEY=your_32_byte_encryption_key_here
      - EMAIL_ENABLED=true
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_FROM_EMAIL=gomft@example.com
      - EMAIL_FROM_NAME=GoMFT
      - EMAIL_ENABLE_TLS=true
      - EMAIL_REQUIRE_AUTH=true
      - EMAIL_USERNAME=smtp_username
      - EMAIL_PASSWORD=smtp_password
      - LOGS_DIR=/app/data/logs
      - LOG_MAX_SIZE=10
      - LOG_MAX_BACKUPS=5
      - LOG_MAX_AGE=30
      - LOG_COMPRESS=true
      - LOG_LEVEL=info
    # The user directive is no longer needed when using PUID/PGID environment variables
```

thanks
