### ISSUE TITLE
Can't create job

### ISSUE THREAD

**Issue by maddox** [StarFleetCPTN/GoMFT#82]
Errors when creating a job.

## Background

1. I originally deployed this via docker and was able to create configs and jobs fine.
2. I started a job and wanted to cancel it, but there's no mechanism to cancel jobs (we need this)
3. So I stopped the docker container, rm -Rf'd the data directories, brought the container back up.
4. Now I'm able to create configs, but not jobs.

## Compose Entry

```yaml
  gomft:
    image: starfleetcptn/gomft:latest
    container_name: gomft
    restart: unless-stopped
    ports:
      - "8202:8080"
    volumes:
      - /home/$USER/docker/gomft/data:/app/data
      - /home/$USER/docker/gomft/backups:/app/backups
      - /home/$USER/docker/.ssh/id_rsa:/id_rsa
      - /home/$USER/docker/.ssh/id_rsa.pub:/id_rsa.pub
      - /home/$USER/docker:/ServerHome
      - nas-backup-10g:/Backup
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVER_ADDRESS=:8080
      - DATA_DIR=/app/data
      - BACKUP_DIR=/app/backups
      - JWT_SECRET=09414f2658678b747eb8032d4da91141f9a4c5f4e4154989a4cd9ccf36342087
      - BASE_URL=http://localhost:8202
      - LOGS_DIR=/app/data/logs
      - LOG_MAX_SIZE=10
      - LOG_MAX_BACKUPS=5
      - LOG_MAX_AGE=30
      - LOG_COMPRESS=true
      - LOG_LEVEL=info
```

## Log

    2025/04/10 09:38:35 job_handlers.go:276: HandleCreateJob: Job.ConfigIDs: 1
    
    2025/04/10 09:38:35 /app/internal/web/handlers/job_handlers.go:310 SQL logic error: no such table: main._transfer_configs_old (1)
    [0.111ms] [rows:0] INSERT INTO `jobs` (`name`,`config_id`,`config_ids`,`schedule`,`enabled`,`last_run`,`next_run`,`webhook_enabled`,`webhook_url`,`webhook_secret`,`webhook_headers`,`notify_on_success`,`notify_on_failure`,`created_by`,`created_at`,`updated_at`) VALUES ("Daily Docker Backup",1,"1","0 4 * * *",true,NULL,NULL,false,"","","",false,false,1,"2025-04-10 09:38:35.942","2025-04-10 09:38:35.942") RETURNING `id`
    
    2025/04/10 09:38:35 job_handlers.go:312: HandleCreateJob: Error creating job: SQL logic error: no such table: main._transfer_configs_old (1)
    [GIN] 2025/04/10 - 09:38:35 | 500 |    4.489345ms |   192.168.1.169 | POST    /jobs
